apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myApp-ReplicaSet
  labels:
    app: myApp
spec:
  selector:
    matchLabels:
      env: production
  replicas: 3
  template:
    metadata:
      metadata:
        name: nginx-2
        labels:
          env: production
      spec:
        containers:
        - name: nginx
          image: nginx